[package]
name = "schema_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0.98", features = ["full", "extra-traits"] }
serde_json = { version = "1.0.138" }
anyhow = "1.0.95"
once_cell = "1.20.3"
